const catalogo = {
    animes: [
        {
            nombre: "Akame ga Kill",
            portada: "IMG/akame.jpg",
            temporadasTotales: 1,
            temporadaActual: 1,
            descripcion: "Algo.",
            valoracion: 9.2,
            color: "#8B0000",
            categorias: ["Acción", "Drama", "Fantasía Oscura", "Shonen"],
            enlaceDescarga: "#",
            tamañoPorCapitulo: "125 MB",
            tamañoTotal: "3.13 GB",
            calidad: "720p",
            capitulos: 25
        },
        {
            nombre: "Ao Ashi",
            portada: "IMG/AoAshi.jpg",
            temporadasTotales: 1,
            temporadaActual: 1,
            descripcion: "Algo.",
            valoracion: 7.5,
            color: "#8B0000",
            categorias: ["Deportes", "Drama", "Romance", "Shonen"],
            enlaceDescarga: "#",
            tamañoPorCapitulo: "120 MB",
            tamañoTotal: "2.89 GB",
            calidad: "720p",
            capitulos: 24
        },
        {
            nombre: "Jujutsu Kaisen",
            portada: "IMG/jujutsu.jpg",
            temporadasTotales: 2,
            temporadaActual: 2,
            descripcion: "Yuji Itadori se une a una organización de hechiceros para combatir maldiciones después de un incidente sobrenatural. Juntos buscarán los dedos de Sukuna mientras protegen al mundo.",
            valoracion: 8.7,
            color: "#4B0082",
            categorias: ["Acción", "Sobrenatural", "Shonen"],
            enlaceDescarga: "#",
            tamañoPorCapitulo: "320 MB",
            tamañoTotal: "3.8 GB",
            calidad: "1080p",
            capitulos: 12
        },
        {
            nombre: "Demon Slayer",
            portada: "IMG/demonslayer.jpg",
            temporadasTotales: 3,
            temporadaActual: 2,
            descripcion: "Tanjiro busca una cura para su hermana Nezuko, convertida en demonio, mientras protege a la humanidad de otras criaturas. Su viaje lo lleva a unirse a los Hashiras.",
            valoracion: 8.9,
            color: "#228B22",
            categorias: ["Acción", "Aventura", "Sobrenatural"],
            enlaceDescarga: "#",
            tamañoPorCapitulo: "380 MB",
            tamañoTotal: "4.5 GB",
            calidad: "1080p BD",
            capitulos: 12
        },
        {
            nombre: "One Piece",
            portada: "IMG/onepiece.jpg",
            temporadasTotales: 20,
            temporadaActual: 15,
            descripcion: "Monkey D. Luffy busca el tesoro One Piece para convertirse en el Rey de los Piratas. En su viaje forma una tripulación y se enfrenta a la Marina y otros piratas.",
            valoracion: 9.0,
            color: "#FF4500",
            categorias: ["Aventura", "Comedia", "Shonen"],
            enlaceDescarga: "#",
            tamañoPorCapitulo: "250 MB",
            tamañoTotal: "150 GB",
            calidad: "720p",
            capitulos: 600
        },
        {
            nombre: "Mushoku Tensei",
            portada: "IMG/mushoku.jpg",
            temporadasTotales: 2,
            temporadaActual: 1,
            descripcion: "Un hombre de 34 años reencarna en un mundo de espadas y magia, decidido a vivir esta nueva vida sin arrepentimientos. Usa sus conocimientos para volverse más fuerte.",
            valoracion: 8.4,
            color: "#9370DB",
            categorias: ["Isekai", "Aventura", "Fantasía", "Magia"],
            enlaceDescarga: "#",
            tamañoPorCapitulo: "360 MB",
            tamañoTotal: "4.3 GB",
            calidad: "1080p",
            capitulos: 12
        },
        {
            nombre: "Chainsaw Man",
            portada: "IMG/chainsaw.jpg",
            temporadasTotales: 1,
            temporadaActual: 1,
            descripcion: "Denji, un joven con deudas, se fusiona con su perro motosierra para convertirse en Chainsaw Man y cazar demonios para una organización gubernamental.",
            valoracion: 8.8,
            color: "#FF0000",
            categorias: ["Acción", "Gore", "Shonen", "Sobrenatural"],
            enlaceDescarga: "#",
            tamañoPorCapitulo: "340 MB",
            tamañoTotal: "4.0 GB",
            calidad: "1080p",
            capitulos: 12
        },
        {
            nombre: "Spy x Family",
            portada: "IMG/spyfamily.jpg",
            temporadasTotales: 2,
            temporadaActual: 1,
            descripcion: "Un espía debe formar una familia falsa para una misión, sin saber que su hija es telépata y su esposa es una asesina. Las identidades secretas chocan en esta comedia de acción.",
            valoracion: 8.6,
            color: "#FF69B4",
            categorias: ["Comedia", "Acción", "Slice of Life"],
            enlaceDescarga: "#",
            tamañoPorCapitulo: "310 MB",
            tamañoTotal: "3.7 GB",
            calidad: "1080p",
            capitulos: 12
        },
        {
            nombre: "Solo Leveling",
            portada: "IMG/sololeveling.jpg",
            temporadasTotales: 1,
            temporadaActual: 1,
            descripcion: "Sung Jin-Woo, el cazador más débil de la humanidad, obtiene un poder único después de sobrevivir a una mazmorra de doble calificación. Ahora puede 'subir de nivel' infinitamente.",
            valoracion: 9.1,
            color: "#4169E1",
            categorias: ["Acción", "Fantasía", "Shonen"],
            enlaceDescarga: "#",
            tamañoPorCapitulo: "380 MB",
            tamañoTotal: "4.5 GB",
            calidad: "1080p",
            capitulos: 12
        }
    ]
};
